### ISSUE TITLE
nginx error.log from /modules/functions.php

### ISSUE THREAD

**Issue by perceptivetek** [NanoTools/nanoNodeMonitor#38]
2018/04/13 14:09:45 [error] 87735#87735: *11480 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: monitors in /var/www/html/monitor/modules/functions.php on line 189
PHP message: PHP Notice:  Undefined property: stdClass::$ in /var/www/html/monitor/modules/functions.php on line 189
PHP message: PHP Notice:  Trying to get property of non-object in /var/www/html/monitor/modules/functions.php on line 189" while reading response header from upstream, client: 98.188.54.10, server: 104.42.100.72, request: "GET /monitor/api.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "rep.nanoisfast.com", referrer: "http://rep.nanoisfast.com/monitor/"

**Comment by ghost** [comment]
Thanks ... that seems a bug in our code that happens when uptimerobot.com is down or the API key is not correct.  Since your "node uptime" currently looks weird at http://rep.nanoisfast.com/monitor/ I think the error is still occuring, correct? 

Please check your API key and this tutorial: https://github.com/NanoTools/nanoNodeMonitor/wiki/Uptimerobot-Node-Monitoring

Will try to reproduce this bug with a wrong API key.

**Comment by ghost** [comment]
Could not really reproduce this on my setup... :(
Can you checkout branch "fix_issue_38" (https://github.com/NanoTools/nanoNodeMonitor/tree/fix_issue_38) and give it a try?
